# SESIÓN 1
S1-EJ2.1: Sesion1/ejercicio2.1.c
	gcc Sesion1/ejercicio2.1.c -o Sesion1/ejercicio2.1_exe
	./Sesion1/ejercicio2.1_exe Sesion1/datos.txt

S1-EJ2.2: Sesion1/ejercicio2.2.c
	gcc Sesion1/ejercicio2.2.c -o Sesion1/ejercicio2.2_exe
	./Sesion1/ejercicio2.2_exe Sesion1/datos.txt

S1-EJ4: Sesion1/ejercicio4.c
	gcc Sesion1/ejercicio4.c -o Sesion1/ejercicio4_exe
	./Sesion1/ejercicio4_exe Sesion1/datos.txt

# SESIÓN 2

S2-T3: Sesion2/ArchivosEjemplo/tarea3.c
	gcc Sesion2/ArchivosEjemplo/tarea3.c -o Sesion2/ArchivosEjemplo/tarea3_exe
	./Sesion2/ArchivosEjemplo/tarea3_exe

S2-EJ2: Sesion2/ejercicio2.c
	gcc Sesion2/ejercicio2.c -o Sesion2/ejercicio2_exe
	./Sesion2/ejercicio2_exe prueba/ 4764

S2-EJ3: Sesion2/ejercicio3.c
	gcc Sesion2/ejercicio3.c -o Sesion2/ejercicio3_exe
	./Sesion2/ejercicio3_exe prueba

S2-EJ4: Sesion2/ejercicio4.c
	gcc Sesion2/ejercicio4.c -o Sesion2/ejercicio4_exe
	./Sesion2/ejercicio4_exe prueba

# SESION 3
S3-P1: Sesion3/ArchivosEjemplo/programa1.c
	gcc Sesion3/ArchivosEjemplo/programa1.c -o Sesion3/ArchivosEjemplo/programa1_exe
	./Sesion3/ArchivosEjemplo/programa1_exe

S3-P2: Sesion3/ArchivosEjemplo/programa2.c
	gcc Sesion3/ArchivosEjemplo/programa2.c -o Sesion3/ArchivosEjemplo/programa2_exe
	./Sesion3/ArchivosEjemplo/programa2_exe	

S3-P3: Sesion3/ArchivosEjemplo/programa3.c
	gcc Sesion3/ArchivosEjemplo/programa3.c -o Sesion3/ArchivosEjemplo/programa3_exe
	./Sesion3/ArchivosEjemplo/programa3_exe	

S3-EJ1: Sesion3/ejercicio1.c
	gcc Sesion3/ejercicio1.c -o Sesion3/ejercicio1_exe
	./Sesion3/ejercicio1_exe 58

S3-EJ4: Sesion3/ejercicio4.c
	gcc Sesion3/ejercicio4.c -o Sesion3/ejercicio4_exe
	./Sesion3/ejercicio4_exe

S3-EJ5: Sesion3/ejercicio5.c
	gcc Sesion3/ejercicio5.c -o Sesion3/ejercicio5_exe
	./Sesion3/ejercicio5_exe

# SESIÓN 4
S4-PFIFO: Sesion4/ArchivosEjemplo/productorFIFO.c
	gcc Sesion4/ArchivosEjemplo/productorFIFO.c -o Sesion4/ArchivosEjemplo/productorFIFO_exe
	./Sesion4/ArchivosEjemplo/productorFIFO_exe fin

S4-CFIFO: Sesion4/ArchivosEjemplo/consumidorFIFO.c
	gcc Sesion4/ArchivosEjemplo/consumidorFIFO.c -o Sesion4/ArchivosEjemplo/consumidorFIFO_exe
	./Sesion4/ArchivosEjemplo/consumidorFIFO_exe

S4-T6: Sesion4/ArchivosEjemplo/tarea6.c
	gcc Sesion4/ArchivosEjemplo/tarea6.c -o Sesion4/ArchivosEjemplo/tarea6_exe
	./Sesion4/ArchivosEjemplo/tarea6_exe

S4-T7: Sesion4/ArchivosEjemplo/tarea7.c
	gcc Sesion4/ArchivosEjemplo/tarea7.c -o Sesion4/ArchivosEjemplo/tarea7_exe
	./Sesion4/ArchivosEjemplo/tarea7_exe

S4-MAESTRO: Sesion4/ejercicio5_maestro.c Sesion4/ejercicio5_esclavo.c
	gcc Sesion4/ejercicio5_esclavo.c -o Sesion4/esclavo_exe -lm
	gcc Sesion4/ejercicio5_maestro.c -o Sesion4/maestro_exe
	./Sesion4/maestro_exe 1000 2000

# SESION 5
S5-T9: Sesion5/ArchivosEjemplo/tarea9.c
	gcc Sesion5/ArchivosEjemplo/tarea9.c -o Sesion5/ArchivosEjemplo/tarea9_exe
	./Sesion5/ArchivosEjemplo/tarea9_exe

S5-T10: Sesion5/ArchivosEjemplo/tarea10.c
	gcc Sesion5/ArchivosEjemplo/tarea10.c -o Sesion5/ArchivosEjemplo/tarea10_exe
	./Sesion5/ArchivosEjemplo/tarea10_exe

S5-RS: Sesion5/ArchivosEjemplo/reciboSignal.c
	gcc Sesion5/ArchivosEjemplo/reciboSignal.c -o Sesion5/ArchivosEjemplo/reciboSignal_exe
	./Sesion5/ArchivosEjemplo/reciboSignal_exe

S5-ES: Sesion5/ArchivosEjemplo/envioSignal.c
	gcc Sesion5/ArchivosEjemplo/envioSignal.c -o Sesion5/ArchivosEjemplo/envioSignal_exe
	./Sesion5/ArchivosEjemplo/envioSignal_exe #Introducir parámetros

S5-EJ3: Sesion5/ejercicio3.c
	gcc Sesion5/ejercicio3.c -o Sesion5/ejercicio3_exe
	./Sesion5/ejercicio3_exe

S5-T12: Sesion5/ArchivosEjemplo/tarea12.c
	gcc Sesion5/ArchivosEjemplo/tarea12.c -o Sesion5/ArchivosEjemplo/tarea12_exe
	./Sesion5/ArchivosEjemplo/tarea12_exe

# EXAMEN
E-EJ1: Examen1/ejercicio1.c
	gcc Examen1/ejercicio1.c -o Examen1/ejercicio1_exe
	./Examen1/ejercicio1_exe prueba

# LIMPIEZA
cleanEXE:
	rm -R Sesion*/*_exe Sesion*/*/*_exe

cleanTXT:
	rm -R Sesion*/*.txt *.txt